"""transactions.is_fixed 추가

Revision ID: 4d5c6dc6ea78
Revises: 5f49d7a279a2
Create Date: 2026-06-30 00:54:11.645063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5c6dc6ea78'
down_revision: Union[str, None] = '5f49d7a279a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_fixed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_fixed')
    # ### end Alembic commands ###
