"""merchant_rules.is_fixed 추가

Revision ID: 6c7df6d214f2
Revises: 4d5c6dc6ea78
Create Date: 2026-07-01 01:03:04.446940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7df6d214f2'
down_revision: Union[str, None] = '4d5c6dc6ea78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_rules', sa.Column('is_fixed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant_rules', 'is_fixed')
    # ### end Alembic commands ###
